### PR TITLE
[WFR] Add initialize method with custom okhttp client

### PR DESCRIPTION
**Pull request by nlgtuankiet**
In this pull request, I made 2 changes
1. Allow initializing with a custom okhttp client, useful for apps that already have an okhttp client. Optimize memory use an allow connection reuse.
2. Defer the default OkHttp client's initialization to the first call (and on background thread too)

All test pass with `gradle testReleaseUnitTest`

### CODE REVIEW

**Comment by nlgtuankiet** [comment]
ops, taking a look at PinnedAmplitudeClient now...

**Comment by nlgtuankiet** [comment]
@djih could you please take a look?

**Comment by haoliu-amp** [comment]
@nlgtuankiet Thanks, we'll review it soon!

**Comment by nlgtuankiet** [comment]
> @nlgtuankiet Thanks, we'll review it soon!

Much appreciated

**Comment by nlgtuankiet** [comment]
let me know when we ready to review, I will resolve the conflict later

**Comment by meghneelgore** [comment]
Can someone please review this? 

I need this functionality since I want to add a Gzip request interceptor to the client since our requests are pretty big.

🙏 🙇

**Review by haoliu-amp — APPROVED** [review]

**Comment by nlgtuankiet** [comment]
Thank you, this means a lot

**Comment by haoliu-amp** [comment]
@nlgtuankiet Sorry for the late review! This change is awesome!

**Pull request merged**
